package dao;

import model.Student;
import java.util.List;

/**
 * Data Access Object (DAO) Interface — Abstraction layer.
 *
 * Defines the contract for all database operations on the Student entity.
 * Having an interface here means we could swap MySQL for another DB
 * without touching the Service or Main layers (Open/Closed Principle).
 *
 * Resume highlight: demonstrates understanding of abstraction and
 * interface-based design in Java.
 */
public interface StudentDAO {

    /**
     * Inserts a new student record into the database.
     * @param student Student object (studentId is auto-generated by DB)
     * @return true if insertion was successful
     */
    boolean addStudent(Student student);

    /**
     * Updates an existing student's details by their ID.
     * @param student Student object with updated fields (studentId must be valid)
     * @return true if at least one row was updated
     */
    boolean updateStudent(Student student);

    /**
     * Deletes a student record by their ID.
     * @param studentId the primary key of the record to delete
     * @return true if at least one row was deleted
     */
    boolean deleteStudent(int studentId);

    /**
     * Fetches all students from the database.
     * @return a List of Student objects (empty list if none exist)
     */
    List<Student> getAllStudents();

    /**
     * Finds a single student by their ID.
     * @param studentId the primary key to search for
     * @return the matching Student, or null if not found
     */
    Student getStudentById(int studentId);

    /**
     * Searches students by course name (case-insensitive partial match).
     * @param course the course name to search for
     * @return a List of matching Student objects
     */
    List<Student> searchByCourse(String course);

    /**
     * Returns all students sorted by marks in descending order.
     * @return sorted List of Student objects
     */
    List<Student> getStudentsSortedByMarks();
}
